db:
  image: mdillon/postgis

web:
  build: .
  command: bash -c "./manage.py runserver 0.0.0.0:8000"
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
  environment:
    - DB_NAME=postgres
    - DB_USER=postgres
    - DB_PORT=5432
    - DB_HOST=db
